#!/bin/bash
# 
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for 
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running. 
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf


# System stuff
if [ -z "$(pgrep xscreensaver)" ] ; then
    xscreensaver -no-splash &
fi

#
# TRAY ICON SOFTWARE
#

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
    nm-applet --sm-disable &
fi

#
# APPLICATION LAUNCHER
#

# Use synapse as our app launcher. (-s: don't display until requested) 
if [ -z "$(pgrep synapse)" ] ; then
    synapse -s &
fi

# Set the background
feh --bg-fill /home/msachtler/Pictures/calvin_galaxy.jpg &

# Load xmodmap for key rebindings
xmodmap ~/.Xmodmap
